### ISSUE TITLE
add logging mechanism for missing translations?

### ISSUE THREAD

**Issue by wolxXx** [delfimov/Translate#3]
hi
i stumbled today over this nice repository and am willing to use this package. 
after setting up successfully the first translations, a feature wish came up :) 

it would be awesome to provide a mechanism that logs missing translations. 
the psr-3 standard may help or directly use the awesome monolog package https://github.com/Seldaek/monolog

if you want me to do this task, tell me more. otherwise it would be great to have this feature in a future release :) 

thx

**Comment by wolxXx** [comment]
hehe ok i've done it already and created a pull request. there is no breaking change and it can be merged instantly.

**Comment by delfimov** [comment]
That's a great idea! Thanks!
