### ISSUE TITLE
Auo-Update fails on packagist

### ISSUE THREAD

**Issue by wolxXx** [delfimov/Translate#8]
hi!
at first: thank you for having the pull request accepted and merged into master and created a new release for it. 
unfortunatly, the new version of this package is not available on packagist. a look there tells me:
"delfimov/translate (Legacy Auto-Update, Needs Attention)"
https://packagist.org/about#how-to-update-packages suggests to add web hooks calls or log in into packagist with github access and let packagist automatically add the web hook calls. 

could you please have a look there?

spacibo!

greetz

**Comment by delfimov** [comment]
Hi! I didn't pay attention to changes in Packagist for some time. Had to relogin using GitHub account and now everything seems ok. 

Thank you for your attention to all the issus around this project! Prost! :)

**Comment by wolxXx** [comment]
yeah, i really like it. smart, clean, small. 
thank you for providing, merging, updating, everything :)
